### ISSUE TITLE
Allow the original RP of a PaymentCredential to update the payment instrument details

### ISSUE THREAD

**Issue by danyao** [rsolomakhin/secure-payment-confirmation#27]
The instrument data (i.e. card art, instrument descriptor) associated with a `PaymentCredential` may become stale over time. It would be useful for the original relying party to be able to update the instrument data.

@tblachowicz: Would you mind adding a bit more details on how you envision this fit into a user flow? Do you want this capability when user visits their bank (the RP)? Are you also thinking of push update without the user visiting the RP's website?

**Comment by ianbjacobs** [comment]
This issue seems to relate to 
 https://github.com/rsolomakhin/secure-payment-confirmation/issues/14

**Comment by danyao** [comment]
Good point. Closing this issue and let's merge the conversation into #14
