### ISSUE TITLE
payment Method versus payment Instruments

### ISSUE THREAD

**Issue by cyberphone** [rsolomakhin/secure-payment-confirmation#33]
From the samples it appears that there is just a payment method and no payment instruments.

If this is correct, the universality of this system will be unnecessary limited.

**Comment by ianbjacobs** [comment]
Payment instruments are being addressed separately.

**Comment by ianbjacobs** [comment]
Closing because instrument storage is not addressed in this version of SPC (by design)

**Comment by cyberphone** [comment]
https://github.com/w3c/webauthn/issues/1570#issuecomment-780611040 shows how this could be done
