### ISSUE TITLE
Test build

### ISSUE THREAD

**Issue by herrjemand** [rsolomakhin/secure-payment-confirmation#37]
Is there a Chrome/Edge/Firefox build that I can play with to test that out yet?

**Comment by ianbjacobs** [comment]
Hi @herrjemand,

Here is some information about the Chrome origin trial:
 https://developer.chrome.com/origintrials/#/view_trial/42784196460019713

It is highly likely that the current "implementation" of SPC (done simply for experimentation) will change significantly. So please do experiment, but know that things will likely change.

Are you ok if we close this issue?

Ian

**Comment by ianbjacobs** [comment]
Hearing no objection, I'll close this issue for now.
