### ISSUE TITLE
What is the purpose of SecurePaymentConfirmationAction?

### ISSUE THREAD

**Issue by adrianhopebailie** [rsolomakhin/secure-payment-confirmation#5]
What is the purpose of `SecurePaymentConfirmationAction`?

It only has a single valid value so it seems redundant.

**Comment by danyao** [comment]
In the future, it may contain "select-and-authenticate" for the [combined instrument selection and authentication](https://docs.google.com/document/d/1n73fdsn8tTDYUGjQPOGRGI_VcTaGNjweedSgcH7P8Hc/edit?ts=5ef93da4&pli=1#heading=h.y7uxuzpcwy0b) flow.

We can also ignore it now, and add the field later, and treat null values as "authenticate".

**Comment by adrianhopebailie** [comment]
> We can also ignore it now, and add the field later, and treat null values as "authenticate".

👍 Seems premature to put something in that may not be used
