### ISSUE TITLE
Authentication versus Authorization

### ISSUE THREAD

**Issue by cyberphone** [rsolomakhin/secure-payment-confirmation#52]
For the coming Task Force to consider.

The core difference between authentication and authorization is that authentication occurs between two end points, while the result of an authorization may be intended for consumption by a party which is not necessarily even known at time the authorization is created.

Another limitation with authentication is that it more or less presumes that data is in clear and that the authenticating party is "trusted".  Merchants are usually not considered as trusted (in computer security terms).

Authorization-based schemes are thus inherently more flexible with respect to backend infrastructure design, but do not combine well with authentication-based schemes like 3DS.

If the authorization path is taken, the most logical foundation would be CTAP2 rather than WebAuthn.

Note: authorization schemes do not depend on externally provided "challenge" data, they rely on locally generated nonce objects and time stamped data making "replay" protection / detection straightforward.  Replay may even be permitted if services are idempotent, for dealing with network glitches and similar temporary outages.

**Comment by ianbjacobs** [comment]
I have not heard anyone indicate that we should include authorization as part of SPC. I have the feeling that data requirements for the SPC signature will be addressed in other issues.
